title: Rajeev Atla
author:
  name: Rajeev Atla
  email: rajeev@rajeevatla.com
description: > # this means to ignore newlines until "show_excerpts:"
  Personal website of an aspring physicist with interests in computational sciences and entrepreneurship.
url: https://rajeevatla.com

show_excerpts: true # set to true to show excerpts on the homepage

# incremental: true # set to true to rebuild only updated pages

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: 
    github:  RajeevAtla
    # devto: 
    # dribbble: 
    # facebook: Rajeev-Atla 
    # flickr:  
    instagram: rat.la
    linkedin: rajeev-atla-891327199
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # keybase: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

    # GitLab instances
    # gitlab:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - Tutoring.md
 - about.md
 - todo.md

markdown: kramdown

# Build settings
theme: minima

plugins:
 - jekyll-seo-tag
 - jemoji
 - jekyll-feed
